/*
 *
 * Study constants
 *
 */

export const REQUEST_STUDY_ACTION = 'app/Study/REQUEST_STUDY_ACTION';
export const RELOAD_STUDY_ACTION = 'app/Study/RELOAD_STUDY_ACTION';
export const DEFAULT_ACTION = 'app/Study/DEFAULT_ACTION';
export const CROWD_ACTION = 'app/Study/CROWD_ACTION';
export const DESCRIPTIVE_ACTION = 'app/Study/DESCRIPTIVE_ACTION';
export const ADMINISTRATIVE_ACTION = 'app/Study/ADMIN_ACTION';
export const RECRUITMENT_ACTION = 'app/Study/RECRUITMENT_ACTION';
export const TRACKING_ACTION = 'app/Study/TRACKING_ACTION';
export const WIKI_ACTION = 'app/Study/WIKI_ACTION';
export const WIKI_SUBMIT_ACTION = 'app/Study/WIKI_SUBMIT_ACTION';
export const TAG_SUBMIT_ACTION = 'app/Study/TAG_SUBMIT_ACTION';
export const TAG_REMOVE_ACTION = 'app/Study/TAG_REMOVE_ACTION';
export const REVIEW_SUBMIT_ACTION = 'app/Study/REVIEW_SUBMIT_ACTION';
export const REVIEWS_RECEIVE_ACTION = 'app/Study/REVIEWS_RECEIVE_ACTION';
export const REVIEW_RECEIVE_ACTION = 'app/Study/REVIEW_RECEIVE_ACTION';
export const REVIEW_UPDATE_ACTION = 'app/Study/REVIEW_UPDATE_ACTION';
export const REVIEW_DELETE_ACTION = 'app/Study/REVIEW_DELETE_ACTION';
export const GET_REVIEW_ACTION = 'app/Study/GET_REVIEW_ACTION';
export const ANNOTATION_CREATE_ACTION = 'app/Study/ANNOTATION_CREATE_ACTION';
export const ANNOTATION_DELETE_ACTION = 'app/Study/ANNOTATION_DELETE_ACTION';
export const ANNOTATION_UPDATE_ACTION = 'app/Study/ANNOTATION_UPDATE_ACTION';
export const SET_WIKI_OVERRIDE_ACTION = 'app/Study/WIKI_OVERRIDE_ACTION';
